import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          I Learn <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          This is my first next.js website ever{' '}
          <code className={styles.code}>Hello World</code>
        </p>

        <div className={styles.grid}>

          <Link href="/joke" >
            <a className={styles.card}>
              <h2>ISR Chuck Norris Joke generator &rarr;</h2>
              <p>This website is build once (SSG) or revalidated using <code>{`/revalidate?secret=<revalidation_token> &route=<route>`}</code></p>
            </a>
          </Link>

          <Link href="/pokemon"> 
            <a className={styles.card}>
              <h2>{`(SSG)`} Pokemons page example &rarr;</h2>
              <p>These pages are generated at <b>build time</b>. Go to <code>{`/pokemon/<id-of-pokemon>`}</code> to see a single pokemon</p>
            </a>
          </Link>

          <Link href="/product" >
            <a className={styles.card}>
              <h2>{`(SSR)`} Products page example &rarr;</h2>
              <p>These pages are generated at <b>every request</b>. Go to <code>{`/product/<id-of-product>`}</code> to see a single pokemon</p>
            </a>
          </Link>

          <Link href="/character" >
            <a className={styles.card}>
              <h2>{`(CSR)`} Breaking Bad characters example &rarr;</h2>
              <p>These pages re generated on <b>client side</b>. Go to <code>{`/character/<id-of-character>`}</code> to see a single character</p>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
